apiVersion: v1
kind: Service
metadata:
  name: bar
  labels:
    app: bar
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30081
    targetPort: 8080
  selector:
    app: bar
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bar-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bar
        version: v1
    spec:
      containers:
      - name: bar
        image: neighbor/bar:latest
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: neighborsecret
